### ISSUE TITLE
Encounter nodejs installation exception so can not go forward

### ISSUE THREAD

**Issue by virgilhuang** [0326/iBookmark#3]
2067 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...e":"^4.4.0","lodash.p'
2067 verbose stack     at JSON.parse (<anonymous>)
2067 verbose stack     at parseJson (/usr/local/lib/node_modules/npm/node_modules/json-parse-better-errors/index.js:7:17)
2067 verbose stack     at consumeBody.call.then.buffer (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/body.js:96:50)
2067 verbose stack     at <anonymous>
2067 verbose stack     at process._tickCallback (internal/process/next_tick.js:188:7)
2068 verbose cwd /Users/hxy/Documents/dev4/iBookmark
2069 verbose Darwin 17.5.0
2070 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "i"
2071 verbose node v8.11.1
2072 verbose npm  v6.0.1
2073 error Unexpected end of JSON input while parsing near '...e":"^4.4.0","lodash.p'
2074 verbose exit [ 1, true ]

**Comment by 0326** [comment]
Now I updated this project, you don't need nodejs and install any dependencies, just clone it and run.
